training_data = [
    ("Sản phẩm tuyệt vời, chất lượng rất tốt!", "tích cực"),
    ("Đóng gói cẩn thận, giao hàng nhanh.", "tích cực"),
    ("Sản phẩm tuyệt vời!", "tích cực"),
    ("Giao hàng nhanh.", "tích cực"),
    ("Lưới đan bị chùng, số kg không đúng yêu cầu. Vợt xước xát nhiều chỗ. Trải nghiệm mua hàng quá tồi tệ.", "tiêu cực"),
    ("Balo rất rộng rãi, chất liệu chống nước xịn xò. Giao hàng nhanh, đóng gói cẩn thận. Rất ưng ý!", "tích cực"),
    ("Vợt công thủ toàn diện, đánh rất thoát cầu. Người mới chơi như mình thấy cực kỳ dễ làm quen.", "tích cực"),
    ("Cước nảy tốt, âm thanh nổ to rất sướng tai. Shop đan đúng số kg yêu cầu. Sẽ ủng hộ!", "tích cực"),
    ("Form rộng thoải mái cho chân bè, đệm êm ái, bám sân cực tốt. Đầu tư hoàn toàn xứng đáng.", "tích cực"),
    ("Quấn cán êm, bám tay, thấm mồ hôi tốt. Mua cả lố về xài dần rất tiết kiệm. Tuyệt vời!", "tích cực"),
    ("Vợt đầm đầu đập cháy sân, thiết kế màu sắc cực đẹp. Cầm lên sân ai cũng phải khen ngợi.", "tích cực"),
    ("Vải áo thấm hút mồ hôi cực tốt, mặc mát mẻ, form dáng chuẩn thể thao. Hàng chính hãng chuẩn.", "tích cực"),
    ("Cầu bay chuẩn, quỹ đạo ổn định, lông khá bền ít bị tưa. Phù hợp cho đánh phong trào tốt.", "tích cực"),
    ("Siêu phẩm tấn công, thân cứng nhưng xoay sở linh hoạt. Đập cầu rất uy lực, đáng đồng tiền.", "tích cực"),
    ("Túi to, đựng được nhiều vợt và giày riêng biệt. Form cứng cáp, khóa kéo trơn tru, màu sắc đẹp.", "tích cực"),
    ("Cước đánh cực nảy, âm thanh đanh thép. Tuy hơi nhanh đứt nhưng cảm giác cầu mang lại rất tuyệt.", "tích cực"),
    ("Khả năng điều cầu và bắt lưới vô cùng xuất sắc. Vợt dễ đánh, cầm vào là quen ngay lập tức.", "tích cực"),
    ("Đôi này bảo vệ cổ chân cực tốt, đệm dày dặn êm ái. Chạy nhảy trên sân rất tự tin.", "tích cực"),
    ("Cây này đánh đôi phản tạt, thủ cầu cực kỳ nhanh và sắc bén. Vợt nhẹ, dễ dàng xoay sở.", "tích cực"),
    ("Đập cầu cháy máy, tấn công cầu sau cực gắt. Bản gen 3 này phối màu nhìn rất sang trọng.", "tích cực"),
    ("Vung vợt nhanh như chớp, tốc độ phản tạt trên lưới không có đối thủ. Màu vàng nổi bật lắm.", "tích cực"),
    ("Cây này điều cầu phản tạt tuyệt vời, thiết kế rất bắt mắt. Đánh xong không bị mỏi tay chút nào.", "tích cực"),
    ("Giày nhẹ, ôm chân tốt, màu sắc trẻ trung. Mức giá này cho một đôi Lining chính hãng là quá hời.", "tích cực"),
    ("Giá rẻ nhưng chất lượng không hề tệ, phù hợp cho người mới tập chơi. Màu sơn khá đẹp và bóng.", "tích cực"),
    ("Huyền thoại đánh đôi là đây. Vung vợt xé gió, phông cầu nhẹ nhàng mà thủ cũng rất chắc chắn.", "tích cực"),
    ("Dùng thấm mồ hôi tốt nhưng hơi dày, làm tăng kích thước cán vợt đáng kể. Dùng tàm tạm được.", "trung lập"),
    ("Hàng giao đúng như mô tả, không có gì đặc biệt xuất sắc. Đóng gói bình thường, giao hàng đúng hẹn.", "trung lập"),
    ("Sản phẩm dùng được, chất lượng tương xứng với tầm giá. Mình cần trải nghiệm thêm mới đánh giá chính xác.", "trung lập"),
    ("Balo thiết kế đẹp nhưng ngăn để giày hơi chật nếu đi size to. Chất lượng gia công ở mức khá.", "trung lập"),
    ("Đánh êm, nảy tốt nhưng mặt cước nhanh chạy và mau chùng. Phải đi chỉnh lại mặt lưới thường xuyên.", "trung lập"),
    ("Vợt nhẹ dễ đánh nhưng thiếu lực đập, chỉ hợp nữ hoặc người mới chơi. Giá rẻ nên không đòi hỏi.", "trung lập"),
    ("Mang êm nhưng form hơi cứng, phải đi vài buổi mới mềm ra và quen chân. Bám sân ở mức ổn.", "trung lập"),
    ("Đánh nhanh tốt nhưng đập cầu thiếu lực, không hợp ai thích tấn công mạnh. Sơn vợt hơi dễ xước nhẹ.", "trung lập"),
    ("Hàng chuẩn, bám tay nhưng dùng một thời gian ngắn là bị chai và trơn. Mau mòn hơn mình nghĩ.", "trung lập"),
    ("Túi rộng nhưng ngăn phụ thiết kế chưa tối ưu lắm. Khóa kéo thỉnh thoảng bị rít, dùng tạm ổn.", "trung lập"),
    ("Vải mặc mát nhưng giặt máy dễ bị xù lông nhẹ. Form áo hơi ôm so với bảng size chuẩn.", "trung lập"),
    ("Cầu bay ổn định nhưng dễ gãy lông nếu đánh vào vành. Tốc độ hơi nhanh so với bình thường.", "trung lập"),
    ("Tiếng nổ to, nảy nhưng đứt quá nhanh, mới 2 tuần đã phải đan lại. Hơi tốn kém chi phí.", "trung lập"),
    ("Đi êm và bám sân nhưng màu trắng cực kỳ dễ bám bẩn. Phải vệ sinh thường xuyên rất mất công.", "trung lập"),
    ("Đập cầu ngon nhưng thân khá cứng, đòi hỏi lực tay khỏe mới thuần được. Ai tay yếu nên cân nhắc.", "trung lập"),
    ("Đánh toàn diện, công thủ đều nhưng không có điểm nào thực sự nổi trội xuất sắc. Phù hợp đánh đôi.", "trung lập"),
    ("Vợt nặng đầu, công ngon nhưng xoay sở phòng thủ hơi chậm. Cần thời gian dài để làm quen nhịp độ.", "trung lập"),
    ("Điều cầu tốt nhưng đập không cắm lắm. Cảm giác đánh hơi nhạt nhòa so với bản Arcsaber 11 đời cũ.", "trung lập"),
    ("Đánh sau sân ngon nhưng bắt lưới khá cồng kềnh. Sơn nhám đẹp nhưng có vẻ dễ bị bong tróc.", "trung lập"),
    ("Vợt vung nhanh nhưng mặt vợt hơi nhỏ, dễ đánh hụt cầu nếu chưa quen. Mức giá này khá chát.", "trung lập"),
    ("Giày quá cứng, đi bị đau hai bên hông chân. Keo dán viền ẩu, mới mang vài bữa đã bung mũi.", "tiêu cực"),
    ("Vợt rung bần bật, đánh rất đau cổ tay. Nước sơn lởm chởm, vừa chạm nhẹ đã xước. Trải nghiệm tệ!", "tiêu cực"),
    ("Giao hàng sai mẫu, nhắn tin cho shop không thấy phản hồi. Dịch vụ chăm sóc khách hàng quá kém cỏi.", "tiêu cực"),
    ("Hàng lỗi ngay từ khi bóc hộp, không sử dụng được. Yêu cầu hoàn tiền nhưng thủ tục cực kỳ rườm rà.", "tiêu cực"),
    ("Balo mỏng manh, khóa kéo kẹt liên tục và đã gãy sau một tuần. Đường chỉ may cẩu thả, bục rách.", "tiêu cực"),
    ("Cước đan chưa được một tuần đã đứt dù đánh phong trào nhẹ nhàng. Chất lượng tệ, không mua lại.", "tiêu cực"),
    ("Quấn cán ra màu dính hết vào tay, giặt không sạch được. Dày cộm khó cầm, vứt luôn sau lần đầu.", "tiêu cực"),
    ("Túi nhận được bị bóp méo mất form, mùi nhựa nồng nặc rất khó chịu. Ngăn lót bên trong bị rách.", "tiêu cực"),
    ("Vải bí, mặc nóng, không hề thấm hút mồ hôi như quảng cáo. Màu áo giặt một lần đã phai nham nhở.", "tiêu cực"),
    ("Cầu dở tệ, đánh nhẹ đã gãy lông, quỹ đạo bay lắc lư lung tung. Tốn tiền, khuyên không nên mua.", "tiêu cực"),
    ("Đệm gót rất cứng, đánh xong đau ê ẩm gót chân. Đế bám sân kém, trơn trượt suýt ngã mấy lần.", "tiêu cực"),
    ("Vợt nhẹ như đồ chơi, thân quá dẻo đánh không có cảm giác cầu. Mới cạch nhẹ đã gãy khung.", "tiêu cực"),
    ("Cán vợt lỏng, kêu lạch cạch khi vung tay. Hoàn thiện cực kém, không xứng đáng với mức giá cao cấp.", "tiêu cực"),
    ("Hàng fake rõ ràng, keo nhem nhuốc, mùi cao su hắc. Form giày méo mó, đi đau hết mũi chân.", "tiêu cực"),
    ("Nhận hàng vợt bị xước sơn một mảng lớn ở góc 12h. Gói hàng sơ sài cẩu thả. Vô cùng thất vọng!", "tiêu cực"),
    ("Mua phải hàng nhái, quấn vào trơn tuột không cầm nổi vợt. Mồ hôi ra là tuột tay ngay, rất nguy hiểm.", "tiêu cực"),
    ("Khung vợt bị nứt chìm ngay từ lúc khui hộp, mang đi đan cước thì sập luôn khung. Tiếc đứt ruột.", "tiêu cực"),
    ("Trọng lượng thực tế sai lệch hẳn so với thông số. Đánh rất nặng nề và rung tay, nghi ngờ hàng giả.", "tiêu cực"),
    ("Sơn dởm, đan cước xong bong tróc te tua ở các lỗ gen. Ngoại hình xuống cấp sau lần đầu sử dụng.", "tiêu cực"),
    ("Lưới đan bị chùng, số kg không đúng yêu cầu. Vợt xước xát nhiều chỗ. Trải nghiệm mua hàng quá tồi tệ.", "tiêu cực")
]

new_text = "Vợt này dở quá, mua về đánh toàn thắng!"